include: package:surf_lint_rules/analysis_options.yaml

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
  rules:
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - always-remove-listener
    - avoid-unrelated-type-assertions
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-unused-parameters
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-const-border-radius
    - prefer-correct-identifier-length:
        exclude:
          - test/**
    - prefer-correct-type-name
    - prefer_extracting_callbacks
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-first
    - prefer-last
    - prefer-single-widget-per-file
    - prefer-conditional-expressions
    - prefer-intl-name
    - provide-correct-intl-args

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    depend_on_referenced_packages: true
    eol_at_end_of_file: true
    noop_primitive_operations: true
    use_test_throws_matchers: true
    # After Dart 2.16.0
    prefer_contains: true
    use_decorated_box: true
    sized_box_shrink_expand: true