name: bottom_inset_observer
version: "2.0.0"
description: A Flutter plugin that helps to listen bottom insets changes (delta since last change, current inset)
repository: "https://github.com/surfstudio/flutter-keyboard-listener"
issue_tracker: "https://github.com/surfstudio/flutter-keyboard-listener/issues"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0
  

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: bottom_inset_observer
  hostUrl:
  separate_repo_url:
